apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  # 必须配置selector，会根据selector选择器找到对应的pod
  selector:
    matchLabels:
      app: logging # pod标签

  template:
    metadata:
      labels:
        app: logging # pod标签
        id: fluentd
      name: fluentd
    spec:
      nodeSelector: # 如果不加nodeSelector，则默认所有节点都运行
        svc: logging-system # node标签
      containers:
        - name: fluentd-es
          image: agilestacks/fluentd-elasticsearch:v1.3.0
          env: # 环境变量
            - name: FLUENTD_ARGS
              value: -qq
          volumeMounts:
            - mountPath: /var/lib/docker/containers # 挂载容器日志目录
              name: containers
            - mountPath: /varlog
              name: varlog
      volumes:
        - hostPath: # 数据集类型，主机路径模式，与node目录共享
            path: /var/lib/docker/containers # node中的共享目录
          name: containers
        - hostPath:
            path: /var/log
          name: varlog
