apiVersion: v1
kind: Pod
metadata:
  name: host-path
  labels:
    app: host-path
spec:
  containers:
    - name: emptydir1
      image: alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /cache1 # 挂载在容器里的路径
          name: cache-volume # 挂载那个volume
    - name: emptydir2
      image: alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /cache2 # 挂载在容器里的路径
          name: cache-volume # 挂载那个volume
  restartPolicy: Always
  volumes:
    - name: cache-volume
      emptyDir: {} # 实现两个容器直接文件共享，当在emptydir1创建文件时也会在/cache2 存在，因为他们两个的共享一个文件常用于日志但是不存在持久化能力