apiVersion: v1
kind: Pod
metadata:
  name: host-path
  labels:
    app: host-path
spec:
  containers:
    - name: host-path
      image: alpine
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /tst-pd # 挂载在容器里的路径
          name: test-volume # 挂载那个volume
  restartPolicy: Always
  volumes:
    - name: test-volume
      hostPath: # 与主机共享目录 （如果宿主机创建、删除和修改也会进行影响容器内部）
        path: /data # 节点目录（宿主机目录）
        type: DirectoryOrCreate # 检查类型，在挂载目录做什么检查类型
        # type: DirectoryOrCreate # 如果目录不存在，则创建
        # type: Directory # 目录
        # type: File # 文件
        # type: FileOrCreate # 如果文件不存在，则创建
        # type: Socket # 套接字
        # type: CharDevice # 字符设备
        # type: BlockDevice # 块设备