apiVersion: v1
kind: Pod
metadata:
  name: config-env
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh","-c","echo $KEY1 && env"]
      env:
        - name: UserName
          valueFrom:
            configMapKeyRef:
              key: username
              name: redis-conf  # configmap 名称
        - name: Pwd # 这里会把configmap里的password映射到容器Pwd环境变量里
          valueFrom:
            configMapKeyRef:
              key: password
              name: redis-conf
  restartPolicy: Never
