apiVersion: apps/v1 # deployment api 版本
kind: Deployment # 资源类型
metadata: # 元信息
  name: nginx-svc
  labels:
    app: nginx-svc
    type: gateway
spec:
  replicas: 2 # 期望副本数
  revisionHistoryLimit: 10 # 保留历史版本
  selector: # 匹配标签，用于找到匹配的replacementSet，也会创建一个 RS 资源类型的
    matchLabels: # 匹配标签
      app: nginx-svc
  template:   # pod模板 也会创建一个 Pod 资源类型
    metadata:
      name: nginx-svc
      labels:
        app: nginx-svc
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
